version: '3.5'

services:
    webpack:
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: dev
        container_name: kickstarter-updates-navigator
        working_dir: "/node/app"
        volumes:
            - .:/node/app
        command: "npm run serve"
        stdin_open: true
        tty: true
        ports:
            - "8069:8080"
        environment:
            - NODE_ENV=development
